-- Version 6: Convert magnitude metrics to DOUBLE PRECISION (MySQL)

ALTER TABLE hotspot_file_scores_metrics 
    MODIFY COLUMN total_commits DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN total_churn DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN contributor_count DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN lines_added DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN lines_deleted DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN recent_commits DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN recent_churn DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN recent_lines_added DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN recent_lines_deleted DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN recent_contributor_count DOUBLE PRECISION NOT NULL,
    MODIFY COLUMN age_days DOUBLE PRECISION NOT NULL;
