package algo

import (
	"math"
	"path/filepath"
	"slices"
	"strings"

	"github.com/huangsam/hotspot/schema"
)

// ComputeScore calculates a file's importance score (0-100) based on its metrics.
// Supports four core scoring modes:
// - hot: Activity hotspots (high recent activity & volatility)
// - risk: Knowledge risk/bus factor (few contributors, high inequality, knowledge decay)
// - complexity: Technical debt candidates (large, old, high total churn)
// - roi: Refactoring ROI (high churn on large files).
func ComputeScore(m *schema.FileResult, mode schema.ScoringMode, weights map[schema.BreakdownKey]float64, thresholdLow, thresholdHigh float64) float64 {
	// DEFENSIVE CHECK: If the file has no content, its score should be 0.
	if m.SizeBytes == 0 {
		return 0.0
	}

	// Tunable maxima to normalize metrics.
	const (
		maxContrib = 20.0    // contributors beyond this saturate
		maxCommits = 500.0   // commits beyond this saturate
		maxSizeKB  = 500.0   // file size in KB beyond this saturate
		maxAgeDays = 3650.0  // ~10 years
		maxChurn   = 5000.0  // total added+deleted lines
		maxRecent  = 50.0    // 50 recent commits is high activity
		maxLOC     = 10000.0 // Lines of Code beyond this saturate (10k lines)
	)

	clamp01 := func(v float64) float64 {
		if v < 0 {
			return 0
		}
		if v > 1 {
			return 1
		}
		return v
	}

	// --- Normalized Metrics [0,1] ---
	nContrib := clamp01(m.UniqueContributors.Float64() / maxContrib)
	nCommits := clamp01(m.Commits.Float64() / maxCommits)
	nSize := clamp01((float64(m.SizeBytes) / 1024.0) / maxSizeKB)
	nAge := clamp01(math.Log1p(m.AgeDays.Float64()) / math.Log1p(maxAgeDays))
	nChurn := clamp01(m.Churn.Float64() / maxChurn)
	nLOC := clamp01(m.LinesOfCode.Float64() / maxLOC) // Normalized Lines of Code

	// Decayed Activity Metrics
	nDecayedCommits := clamp01(m.DecayedCommits.Float64() / maxCommits)
	nDecayedChurn := clamp01(m.DecayedChurn.Float64() / maxChurn)

	// Inverted Metrics
	nGiniRaw := clamp01(m.Gini)            // Gini (raw: high is bad)
	nInvContrib := clamp01(1.0 - nContrib) // Inverse Contributors (high is bad/risky)
	nRecentCommits := clamp01(m.RecentCommits.Float64() / maxRecent)
	nInvRecentCommits := clamp01(1.0 - nRecentCommits) // Inverse Recent Activity (high indicates low activity)

	// --- Recency Signal Calculation ---
	// Freshness ratio: how much of the lifetime volume is recent (fixed window)?
	// We weight commits more heavily (0.7) than churn (0.3) to avoid
	// single massive 'reformatting' commits from over-inflating the signal.
	commitRatio := 0.0
	if m.Commits > 0 {
		commitRatio = m.RecentCommits.Float64() / m.Commits.Float64()
	}
	churnRatio := 0.0
	if m.Churn > 0 {
		churnRatio = m.RecentChurn.Float64() / m.Churn.Float64()
	}
	m.RecencySignal = clamp01((commitRatio * 0.7) + (churnRatio * 0.3))
	m.RecencyThresholdLow = thresholdLow
	m.RecencyThresholdHigh = thresholdHigh

	// --------------------------------

	var raw float64

	// Get weights for the mode
	// weights := GetWeightsForMode(mode, customWeights)

	// Ensure ModeBreakdown is initialized with appropriate capacity
	if m.ModeBreakdown == nil {
		m.ModeBreakdown = make(map[schema.BreakdownKey]float64, 8) // max across all modes
	}
	breakdown := m.ModeBreakdown

	// Clear any previous entries
	clear(breakdown)

	// Build breakdown by applying weights to normalized metrics
	// Default to raw volume unless the mode specifically benefits from decay
	finalCommits := nCommits
	finalChurn := nChurn

	if mode == schema.HotMode || mode == schema.ROIMode {
		finalCommits = nDecayedCommits
		finalChurn = nDecayedChurn
	}

	breakdown[schema.BreakdownAge] = weights[schema.BreakdownAge] * nAge
	breakdown[schema.BreakdownChurn] = weights[schema.BreakdownChurn] * finalChurn
	breakdown[schema.BreakdownCommits] = weights[schema.BreakdownCommits] * finalCommits
	breakdown[schema.BreakdownContrib] = weights[schema.BreakdownContrib] * nContrib
	breakdown[schema.BreakdownSize] = weights[schema.BreakdownSize] * nSize

	// Mode-specific metrics
	switch mode {
	case schema.RiskMode:
		breakdown[schema.BreakdownGini] = weights[schema.BreakdownGini] * nGiniRaw
		breakdown[schema.BreakdownInvContrib] = weights[schema.BreakdownInvContrib] * nInvContrib
		breakdown[schema.BreakdownLOC] = weights[schema.BreakdownLOC] * nLOC
		breakdown[schema.BreakdownLowRecent] = weights[schema.BreakdownLowRecent] * nInvRecentCommits
	case schema.ComplexityMode:
		breakdown[schema.BreakdownLOC] = weights[schema.BreakdownLOC] * nLOC
		breakdown[schema.BreakdownLowRecent] = weights[schema.BreakdownLowRecent] * nInvRecentCommits
	case schema.ROIMode:
		breakdown[schema.BreakdownGini] = weights[schema.BreakdownGini] * nGiniRaw
		breakdown[schema.BreakdownLOC] = weights[schema.BreakdownLOC] * nLOC
	}

	for _, value := range breakdown {
		raw += value
	}
	score := raw * 100.0

	pathLower := strings.ToLower(m.Path)
	extLower := strings.ToLower(filepath.Ext(m.Path))

	// Debuff signals on tests, autogenerated code, mock code and example code
	if strings.Contains(pathLower, "test") || strings.Contains(pathLower, "generate") || strings.Contains(pathLower, "example") || strings.Contains(pathLower, "mock") {
		if mode == schema.RiskMode {
			score *= 0.75
		} else {
			score *= 0.50
		}
	}

	// Debuff signals on configuration
	if isConfigurationFile(extLower) {
		if mode == schema.ComplexityMode {
			score *= 0.50
		}
	}

	// Scale breakdown values to percent contributions
	for k, v := range breakdown {
		breakdown[k] = v * 100.0
	}

	// Generate natural language reasoning based on the breakdown
	m.Reasoning = computeReasoning(m, mode)

	return score
}

// computeReasoning translates the numerical ModeBreakdown into an array of semantic justifications.
func computeReasoning(m *schema.FileResult, mode schema.ScoringMode) []string {
	var results []string
	b := m.ModeBreakdown

	// Constants for threshold-based reasoning
	const (
		significant = 20.0 // 20% contribution is "significant"
		dominant    = 30.0 // 30% contribution is "dominant"
	)

	// 1. Core Synthesis Patterns (Cross-metric logic)
	gini, hasGini := b[schema.BreakdownGini]
	age, hasAge := b[schema.BreakdownAge]
	lowRecent, hasLowRecent := b[schema.BreakdownLowRecent]
	loc, hasLoc := b[schema.BreakdownLOC]
	churn, hasChurn := b[schema.BreakdownChurn]

	// Pattern: Institutional Amnesia (High Gini/Risk + High Age + Low Activity)
	if hasGini && gini > significant && hasAge && age > significant && hasLowRecent && lowRecent > significant {
		results = append(results, "Institutional Amnesia: Vital logic is concentrated in inactive authors with high maintenance decay.")
	}

	// Pattern: Volatile Anchor (High Churn + High LOC)
	if hasChurn && churn > dominant && hasLoc && loc > significant {
		results = append(results, "Volatile Anchor: Large module undergoing massive frequent changes; high refactoring ROI.")
	}

	// Pattern: Knowledge Silo (High Inverse Contrib or Gini)
	if (hasGini && gini > dominant) || (b[schema.BreakdownInvContrib] > dominant) {
		results = append(results, "Knowledge Silo: File ownership is dangerously concentrated in too few people.")
	}

	// 2. Fallback: Metric-Specific Logic (if no pattern matched or to add detail)
	if len(results) < 2 {
		if b[schema.BreakdownChurn] > significant {
			msg := "High Churn: High cumulative volatility identifies this file as a historical bottleneck."
			if m.RecencySignal > m.RecencyThresholdHigh {
				msg = "High Churn: Recent volatility indicates this file is currently a development bottleneck."
			} else if m.RecencySignal < m.RecencyThresholdLow {
				msg = "Historical Hotspot: Massive cumulative churn, but activity has stabilized recently."
			}
			results = append(results, msg)
		}
		if hasLowRecent && lowRecent > significant {
			results = append(results, "Knowledge Decay: File has not been updated recently, increasing the risk of institutional amnesia.")
		}
		if hasLoc && loc > significant {
			results = append(results, "Structural Complexity: High lines of code count increases cognitive load for maintainers.")
		}
	}

	// 3. Mode-Specific Nuance
	if mode == schema.ROIMode {
		if churn > significant && loc > significant {
			results = append(results, "High Conflict Tax: Parallel development in a large file is creating a coordination overhead.")
		}
		if hasGini && gini > significant {
			results = append(results, "Knowledge Fragility: High financial risk if the primary code owners are unavailable.")
		}
	}

	if mode == schema.RiskMode && len(results) == 0 {
		results = append(results, "Ownership Risk: Low contributor diversity identified for this resource.")
	}

	return results
}

// Gini calculates the Gini coefficient for a set of values.
// The Gini coefficient measures inequality in a distribution, ranging from 0 (perfect equality)
// to 1 (perfect inequality). It's used here to measure how evenly distributed commits are
// among contributors.
func Gini(values []float64) float64 {
	n := len(values)
	if n <= 1 {
		return 0
	}

	// Sort values in non-decreasing order
	slices.Sort(values)

	var sum float64
	var weightedSum float64
	for i, v := range values {
		sum += v
		// Note: i is 0-indexed, so we use (i+1) for 1-based indexing in formula
		weightedSum += float64(i+1) * v
	}

	if sum == 0 {
		return 0
	}

	// G = (2 * sum(i * x_i)) / (n * sum(x_i)) - (n + 1) / n
	// where x_i are sorted values.
	nFloat := float64(n)
	g := (2*weightedSum)/(nFloat*sum) - (nFloat+1)/nFloat

	return math.Min(math.Max(g, 0), 1) // clamp to [0,1]
}

// isConfigurationFile returns true if the extension belongs to a data or configuration format.
func isConfigurationFile(ext string) bool {
	// Remove leading dot if present
	ext = strings.TrimPrefix(ext, ".")

	return slices.Contains([]string{
		"yml", "yaml", "json", "toml", "cfg", "xml", "ini",
		"lock", "sum", "csv", "tsv", "md", "txt", "tfstate",
	}, ext)
}
