package internal

import (
	"context"
	"time"

	"github.com/stretchr/testify/mock"
)

// MockGitClient is an autogenerated mock type for the GitClient type.
type MockGitClient struct {
	mock.Mock
}

var _ GitClient = &MockGitClient{} // Compile-time check

// Run implements the GitClient interface.
func (m *MockGitClient) Run(ctx context.Context, repoPath string, args ...string) ([]byte, error) {
	var mockArgs []any
	mockArgs = append(mockArgs, ctx, repoPath)
	for _, arg := range args {
		mockArgs = append(mockArgs, arg)
	}
	ret := m.Called(mockArgs...)
	output, _ := ret.Get(0).([]byte)
	return output, ret.Error(1)
}

// GetActivityLog implements the GitClient interface.
func (m *MockGitClient) GetActivityLog(ctx context.Context, repoPath string, startTime, endTime time.Time) ([]byte, error) {
	ret := m.Called(ctx, repoPath, startTime, endTime)
	output, _ := ret.Get(0).([]byte)
	return output, ret.Error(1)
}

// GetCommitTime implements the core.GitClient interface.
func (m *MockGitClient) GetCommitTime(ctx context.Context, repoPath string, ref string) (time.Time, error) {
	ret := m.Called(ctx, repoPath, ref)
	t, _ := ret.Get(0).(time.Time)
	return t, ret.Error(1)
}

// GetFileActivityLog implements the GitClient interface.
func (m *MockGitClient) GetFileActivityLog(ctx context.Context, repoPath string, path string, startTime, endTime time.Time, follow bool) ([]byte, error) {
	ret := m.Called(ctx, repoPath, path, startTime, endTime, follow)
	content, _ := ret.Get(0).([]byte)
	return content, ret.Error(1)
}

// GetRepoRoot implements the GitClient interface.
func (m *MockGitClient) GetRepoRoot(ctx context.Context, contextPath string) (string, error) {
	ret := m.Called(ctx, contextPath)
	root, _ := ret.Get(0).(string)
	return root, ret.Error(1)
}

// ListFilesAtRef implements the GitClient interface.
func (m *MockGitClient) ListFilesAtRef(ctx context.Context, repoPath string, ref string) ([]string, error) {
	ret := m.Called(ctx, repoPath, ref)
	files, _ := ret.Get(0).([]string)
	return files, ret.Error(1)
}
