name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', '1.25']

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Full history for git log commands

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4

    - name: Run tests
      run: make test

    - name: Run build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hotspot-go${{ matrix.go-version }}
        path: hotspot
